import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Background */}
        <div className="absolute w-full h-full -z-10 bg-[url('/bg.png')] bg-cover bg-center opacity-100"></div>

        {/* Main Content */}
        <main className=" min-h-screen mx-auto container">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-black bg-opacity-60 text-white px-4 py-6">
          <div className="mx-auto text-center px-4 text-gray-300">
            © {new Date().getFullYear()} Blue Onion. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
